


export const CREATE_EMPLOYE_START = "CREATE_EMPLOYE_START";
export const CREATE_EMPLOYE_SUCCESS = "CREATE_EMPLOYE_SUCCESS";
export const CREATE_EMPLOYE_ERROR = "CREATE_EMPLOYE_ERROR";
 
export const LOAD_EMPLOYE_START = "LOAD_EMPLOYE_START";
export const LOAD_EMPLOYE_SUCCESS = "LOAD_EMPLOYE_SUCCESS";
export const LOAD_EMPLOYE_ERROR = "LOAD_EMPLOYE_ERROR";
 
export const UPDATE_EMPLOYE_START = "UPDATE_EMPLOYE_START";
export const UPDATE_EMPLOYE_SUCCESS = "UPDATE_EMPLOYE_SUCCESS";
export const UPDATE_EMPLOYE_ERROR = "UPDATE_EMPLOYE_ERROR";
 
export const DELETE_EMPLOYE_START = "DELETE_EMPLOYE_START";
export const DELETE_EMPLOYE_SUCCESS = "DELETE_EMPLOYE_SUCCESS";
export const DELETE_EMPLOYE_ERROR = "DELETE_EMPLOYE_ERROR";